### ISSUE TITLE
USB Device not recognised

### ISSUE THREAD

**Issue by cymplecy** [codebugtools/codebug_tether#1]
Getting this error message after loading the tether firmware

Loading in a normal .cbg file works fine

http://snag.gy/GDsTQ.jpg

Its showing up as having an Invalid Configuration Descriptor in Windows device manager
using Win 8.1 64bit

**Comment by tompreston** [comment]
Thanks, we're looking into this.

**Comment by tompreston** [comment]
We've fixed the issue on Linux, can you let us know what it looks like on Windows?

**Comment by cymplecy** [comment]
No error when physically connecting now - off to try and see if I can talk to it :-)

**Comment by cymplecy** [comment]
And got the binary counting python prog runnning :-)

**Comment by tompreston** [comment]
Cool! Saw your tweet as well. Thanks. :)
