### ISSUE TITLE
PWM output 3x expected frequency

### ISSUE THREAD

**Issue by jam3sward** [codebugtools/codebug_tether#15]
Using codebug_tether with pwm_freq(1000) the actual output frequency appears to be 3kHz on an oscilloscope. Similarly, using pwm_freq(2000) actually outputs 6kHz. This seems to reproduce on both 0.7.0 and 0.7.3 firmware. However, when using a code block with "start tone (Hz) [1000]" the output is exactly 1kHz on the oscilloscope as expected.

The code used is as follows:
cb = codebug_tether.CodeBug()
cb.set_leg_io(0, IO_PWM_OUTPUT)
cb.pwm_freq(1000)
time.sleep(2)
cb.pwm_off()

**Comment by tompreston** [comment]
Thanks for raising this. I know what the issue is and the fix will be pushed in the next update (coming very soon!).

**Comment by jam3sward** [comment]
Thanks Tom, that's great news!

**Comment by jam3sward** [comment]
Thanks for looking at this, it hadn't occurred to me that the clock frequency was 12MHz rather than 4MHz.
I can confirm that the output frequency now matches the parameter passed to pwm_freq(), although the available frequency range has been reduced as a result. For example, 1kHz is no longer possible because (750000 / 1000 - 1) = 749 which is too large for the 8-bit value expected by pwm_on(). However, higher frequencies such as 3kHz work correctly. It looks like the minimum frequency is now about 2920Hz with the current implementation.
Assuming this is a PIC, it looks like the minimum possible frequency with the hardware at 12MHz clock would be 732.42Hz with PR2=0xFF, T2CON=0x07, CCPR1L=0x7F and CCP1CON=0x3C. I might have a play with the Python code to try this.

**Comment by tompreston** [comment]
I think you're assuming a 10-bit resolution for the timer since this is how the duty cycle is calculated. However period is calculated using just the 8-bit PR2 value.

(48,000,000 Fosc / 4) / 16 pre-scaler = 750,000 timer 'ticks' per second. If PR2 is set at a maximum of 0xFF then that's 750k / (0xFF + 1) = 2929.6875 Hz

See section 15.3.4 in the device manual.
http://ww1.microchip.com/downloads/en/DeviceDoc/30684A.pdf

I hope that helps!

**Comment by jam3sward** [comment]
I was assuming Fosc = 12MHz and plugging into the equation under 15-1 in section 15.3.3 of the PIC manual, but it looks like Fosc = 48MHz? That would explain the factor of 4 difference! The blockly version at codebug.org.uk does allow frequencies below 1kHz, so I guess a different clock frequency may be configured there?

To explain the context to all this, I was trying to get lower frequency notes out of the CodeBug.

**Comment by tompreston** [comment]
USB requires 48MHz - if we didn't have it this fast then you wouldn't be able to talk to CodeBug at all! Programs from the website run slower in order to reduce power (16MHz).

**Comment by jam3sward** [comment]
OK that makes perfect sense, thank you. It was actually the web-site version I was originally looking at, and where I was hoping to get lower frequency notes, and that's what led me to look at codebug_tether. Now I can appreciate that isn't possible (at least without further reducing the clock, or doing it in software). Thanks for responding anyway.
