### ISSUE TITLE
How do I wire my Codebug to my Raspberry Pi?

### ISSUE THREAD

**Issue by DougieLawson** [codebugtools/codebug_tether#2]
I can see how the code gets installed, I can get the cbg file installed on my Codebug all from my Raspberry Pi (it appears as /dev/sda1 when I hold button A and plug it in). But, the missing piece is how to wire RPi pins #8 (TXD), #10 (RXD) & #6 (GND) to my Codebug. 

Or if I use a FTDI USB serial how to wire TXD, RXD and GND to the Codebug. 

Do I need to be worried about 3V3 vs 5V0?

I've got the same issue with your I2C tethering.

**Comment by tompreston** [comment]
Hi,
After loading the cbg file onto CodeBug it should appear as a USB serial device (at `/dev/ttyACM0`, on Linux) when you plug it in via USB. You don't have to hold any buttons and there is no wiring necessary.

Hm, I probably should have mentioned this in the docs... I'll fix that now! Haha!

**Comment by DougieLawson** [comment]
Thank you.
