### ISSUE TITLE
Control of CodeBug LEG state not working as expected

### ISSUE THREAD

**Issue by DeeJay** [codebugtools/codebug_tether#9]
Test case:
PS C:\Users\David\Documents\GitHub\codebug_tether> python
ActivePython 2.7.6.9 (ActiveState Software Inc.) based on
Python 2.7.6 (default, Feb 27 2014, 14:15:49) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

> > > from codebug_tether import CodeBug
> > > cb = CodeBug('com6')
> > > cb.set_leg_io(0, 0)
> > > cb.set_output(0,1)
> > > cb.set_leg_io(1, 0)
> > > cb.set_output(1,1)
> > > cb.set_leg_io(2, 0)
> > > cb.set_output(2,1)
> > > exit()
> > > PS C:\Users\David\Documents\GitHub\codebug_tether> 

The effect of this is that each of the 3 Legs is set HIGH in turn, but is reset to LOW when the next Leg in the sequence is set HIGH, so at the end of the test only Leg2 is High.

I expected each Leg to be set/cleared independently.

Is this a bug, or have I misunderstood the intent of the API? If the latter, is there a simple way to set/reset each Leg independently please?

[This is using **version** = '0.4.1' of the codebug_tether module and associated .cbg firmware.]

**Comment by tompreston** [comment]
This was a bug. I've fixed it now, thanks for pointing it out.
